import Animation from '@/components/atmos/Animation';
import MainTap from '@/components/molecules/MainTap';
import { useState } from 'react';
import MainBlock from '../components/organisms/MainBlock';

export default function Quotes() {
  const [activeTab, setActiveTab] = useState<number>(1);
  return (
    <main>
      <section className="flex w-full min-w-[400px] mx-auto flex-col sm:flex-row mt-20 items-start justify-around ">
        <div className="flex flex-col min-w-[350px] pr-20 text-2xl font-bevietnam my-20 sm:my-auto">
          {activeTab === 1 && (
            <h1 className="font-bold whitespace-nowrap">
              키워드 퀴즈로 면접에 대비하세요!
            </h1>
          )}
          {activeTab === 2 && (
            <h1 className="font-bold whitespace-nowrap">
              가상 면접으로 준비하세요!
            </h1>
          )}
          <MainTap activeTab={activeTab} setActiveTab={setActiveTab} />
        </div>
        <div>
          <Animation activeTab={activeTab} />
        </div>
      </section>
      <section>
        <MainBlock />
      </section>
    </main>
  );
}

// export const getStaticProps: GetStaticProps<Props> = async () => {
//   const initialQuote = await fetchQuotes();
//   return {
//     props: {
//       initialQuote: initialQuote.slip.advice,
//     },
//   };
// };

//헤드 설정 잊지말것
{
  /* <main className="mx-auto flex flex-col items-center"> */
}
{
  /* <Head>
<title>Create Next App</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon.ico" />
</Head> */
}
//기술면접 사진과 화상면접 사진 넣기
// ISR 오래걸림
