import Animation from '@/components/atmos/Animation';
import MainTap from '@/components/molecules/MainTap';
import { useState } from 'react';
export default function Quotes() {
  const [activeTab, setActiveTab] = useState<number>(1);
  return (
    <main className="flex">
      <section className="flex flex-col items-center">
        {activeTab === 1 && <h1>퀴즈</h1>}
        {activeTab === 2 && <h1>화상면접</h1>}
        <MainTap activeTab={activeTab} setActiveTab={setActiveTab} />
      </section>
      <div>
        <Animation activeTab={activeTab} />
      </div>
    </main>
  );
}

// export const getStaticProps: GetStaticProps<Props> = async () => {
//   const initialQuote = await fetchQuotes();
//   return {
//     props: {
//       initialQuote: initialQuote.slip.advice,
//     },
//   };
// };

//헤드 설정 잊지말것
{
  /* <main className="mx-auto flex flex-col items-center"> */
}
{
  /* <Head>
<title>Create Next App</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon.ico" />
</Head> */
}
//기술면접 사진과 화상면접 사진 넣기
// ISR 오래걸림
